//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalAuth.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalAuth.Application.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account in this application doesn&apos;t exists. Do you want create ?.
        /// </summary>
        public static string Error_AccountDoesNotExists {
            get {
                return ResourceManager.GetString("Error_AccountDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists in this app..
        /// </summary>
        public static string Error_AccountExists {
            get {
                return ResourceManager.GetString("Error_AccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &apos;{0}&apos; doesn&apos;t exists..
        /// </summary>
        public static string Error_AppDoesNotExists {
            get {
                return ResourceManager.GetString("Error_AppDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not available..
        /// </summary>
        public static string Error_AppInactive {
            get {
                return ResourceManager.GetString("Error_AppInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account in this apllication is blocked..
        /// </summary>
        public static string Error_BlockedAccount {
            get {
                return ResourceManager.GetString("Error_BlockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is inactive..
        /// </summary>
        public static string Error_InactiveUser {
            get {
                return ResourceManager.GetString("Error_InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email exists..
        /// </summary>
        public static string Error_UserEmailExsists {
            get {
                return ResourceManager.GetString("Error_UserEmailExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        public static string Success_RegisterUser {
            get {
                return ResourceManager.GetString("Success_RegisterUser", resourceCulture);
            }
        }
    }
}
